add_executable(Block_cut_1.1 Block_cut_1.1.f90)
add_executable(check-mesh-ver1.1 check-mesh-ver1.1.f90)
add_executable(comput-Q-ec1.0 comput-Q-ec1.0.f90)
add_executable(convert_inp convert_inp.f90)
add_executable(convert-cgns-inp-1.2 convert-cgns-inp-1.2.f90)
add_executable(convertMesh2d-3d-v1.1 convertMesh2d-3d-v1.1.f90)
add_executable(convertXYZ-ver1.1 convertXYZ-ver1.1.f90)
add_executable(get_bcin_v1.4.2 get_bcin_v1.4.2.f90)
add_executable(In2inp-1.1 In2inp-1.1.f90)
add_executable(partation-1.2 partation-1.2.f90)
add_executable(PlotZplane-1.3a PlotZplane-1.3a.f90)
add_executable(readflow3d-ver2.5 readflow3d-ver2.5.f90)
add_executable(readflow3d-wing readflow3d-wing.f90)

# 链接 CGNS 库
target_compile_options(convert-cgns-inp-1.2 PRIVATE "-cpp")
target_include_directories(convert-cgns-inp-1.2 PRIVATE ${CMAKE_SOURCE_DIR}/3rdparty/CGNS-3.1.4/build/src)
target_link_directories(convert-cgns-inp-1.2 PRIVATE ${CMAKE_SOURCE_DIR}/3rdparty/CGNS-3.1.4/build/src)
target_link_libraries(convert-cgns-inp-1.2 cgns)

# 设置可执行文件的输出目录
set_target_properties(Block_cut_1.1 PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set_target_properties(check-mesh-ver1.1 PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set_target_properties(comput-Q-ec1.0 PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set_target_properties(convert_inp PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set_target_properties(convert-cgns-inp-1.2 PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set_target_properties(convertMesh2d-3d-v1.1 PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set_target_properties(convertXYZ-ver1.1 PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set_target_properties(get_bcin_v1.4.2 PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set_target_properties(In2inp-1.1 PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set_target_properties(partation-1.2 PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set_target_properties(PlotZplane-1.3a PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set_target_properties(readflow3d-ver2.5 PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set_target_properties(readflow3d-wing PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)